@MagicVilla_VillaAPI_HostAddress = http://localhost:5228

GET {{MagicVilla_VillaAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{MagicVilla_VillaAPI_HostAddress}}/VillaAPI/GetAll
Accept: application/json